<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectLowest to HighestHighest to Lowest</name>
   <tag></tag>
   <elementGuidId>c94bcca7-8717-44ab-a2ad-8a9e7b58cf1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dropdownSelector']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdownSelector</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>91dc0cca-4ad0-40c2-b260-3bd782117de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownSelector</value>
      <webElementGuid>eadbb332-6700-4e99-a015-c7767e684939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border ml-2 p-2</value>
      <webElementGuid>eae38387-ae86-418c-8a42-117c99e4f41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectLowest to HighestHighest to Lowest</value>
      <webElementGuid>cc21c20f-b12a-49d3-93d7-d47c5559d983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownSelector&quot;)</value>
      <webElementGuid>37f898d7-0700-41f0-8508-ea9d3bb85a70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dropdownSelector']</value>
      <webElementGuid>bcdfc829-f5ca-4f82-900b-14b9e5a0af3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/select</value>
      <webElementGuid>847155e5-4bdd-4b94-86a1-ff79d36f9eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/following::select[1]</value>
      <webElementGuid>8369ad66-3190-4d3d-8c99-bc855cf037bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toy shop'])[1]/following::select[1]</value>
      <webElementGuid>8bdf8d62-c556-423f-b503-453eee223fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Cart'])[1]/preceding::select[1]</value>
      <webElementGuid>4bcd4e65-9f96-4c44-add4-21e8dc8a6a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Cart'])[2]/preceding::select[1]</value>
      <webElementGuid>8e78a6d3-89b4-4ea0-b0d9-ffe53f4f23ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>956e2ef1-f916-4457-8dc6-14ace4ddd97a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dropdownSelector' and (text() = 'SelectLowest to HighestHighest to Lowest' or . = 'SelectLowest to HighestHighest to Lowest')]</value>
      <webElementGuid>6c8d3078-d88a-4218-a1ff-111d0d0e31b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
